### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by an1018** [yeguixin/captcha_solver#1]
@yeguixin I am very interested in your paper, but which part of the code is generated synthetic captchas without background consusion?
And where is the preprocessing code?
I look forward to your reply.Thanks you very much！

**Comment by yeguixin** [comment]
Hi, currently we only public the transfer learning code. The preprocessing code and synthetic code are not published considering the abusing and security.

**Comment by an1018** [comment]
@yeguixin Your article refers to the discriminator network defined in [52],do you use local discriminator rather than defining a globaldiscriminator network and upadate disciminator using a history refined images too.

**Comment by ainmsss** [comment]
but I think you should publish all your code to press people and organizations to adjust their security means as soon as possible
