### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by lixiilu** [yeguixin/captcha_solver#3]
Your article is great, but when I run the code I find that there is no dataset. That is my question . Looking forward to your reply.

**Comment by yeguixin** [comment]
Thanks for your attention. I have not get the authorization of the target websites to publish the real capthas. Sorry for this. Anyway, I can send you some synthetic captchas if you need.

**Comment by lixiilu** [comment]
@yeguixin Thank you for your kindness, but it may not be needed for the time being. I'm sorry to bother you
