### ISSUE TITLE
Is this code complete?

### ISSUE THREAD

**Issue by ainmsss** [yeguixin/captcha_solver#5]
I browse the paper and the code but cant find any GAN mechanism in it。the paper say 
"Our captcha generator model includes a image generator and a generator network. The image generator produces a captcha image at the word level, and the generator network modifies the produced captcha image at the pixel level to add security features."
       But there is only a keras image generator in your code without any generator network. Cant find any trace of GAN

**Comment by yeguixin** [comment]
Sorry, we haven't public the captcha generator. We only open the solver as you can find in src folder.
