### ISSUE TITLE
How do you get the labels of synthesized captchas?

### ISSUE THREAD

**Issue by sun98** [yeguixin/captcha_solver#6]
Sorry for disturbing. Would you mind explaining how you get the labels of the synthesized captchas?
![image](https://user-images.githubusercontent.com/18310020/50448480-84226a80-095c-11e9-971a-c3e8bf2e54a0.png)

**Comment by yeguixin** [comment]
The captcha synthesizer includes a captcha image generators which can automatically generates captcha images according to a given captcha word and parameter setting.  Here the captcha word is the label.

**Comment by scut-salmon** [comment]
How to get the parameter setting, is it set manually?

**Comment by yeguixin** [comment]
Hi, you can refer to this [reponse](https://github.com/yeguixin/captcha_solver/issues/7#issuecomment-453035545)
